### ISSUE TITLE
printf output not redirected

### ISSUE THREAD

**Issue by mikecroucher** [jupyter-xeus/xeus-cling#112]
If I do 

```
#include <stdio.h>
printf("testing")
```

In the notebook, I get the return value of the `printf` function which in this case is 

```
(int) 7
```
but the string `testing` does not appear anywhere.

This, in turn, causes problems when trying to use a C library that makes use of `printf`.  Functions that were verbose in real usage are silent in the notebook.

**Comment by SylvainCorlay** [comment]
Thanks for reporting. Indeed we correctly redirect the output of `std::cout` and `std::cerr` but not the C-level `stdout` output.

**Comment by liudonghua123** [comment]
This is really an urgency issue. Any ideas how to fix it.
I tried the pure cling c++ kernel, its `printf` functions well.
See more on https://github.com/root-project/cling/tree/master/tools/Jupyter

**Comment by SylvainCorlay** [comment]
The current kernel in the cling project actually does not do a redirection. It pipes to the (almost) unchanged interpreter and capture the output in this way.

We really embed cling as a library, which enables many things such as rich display and widgets and much more. However redirecting C-level streams will be more complicated.

**Comment by liqg** [comment]
I also think capturing c-level stdout and stderr is very important, otherwise, many C libraries do not work well.

**Comment by jurajmichalak1** [comment]
Thank you very much for this project, but without output redirection it makes no sense to use it for anything real. Is this issue still open or does it have any solution / configuration option?

**Comment by SylvainCorlay** [comment]
@jurajmichalak1 if you use `std::cout` / `std::clog` / `std::cerr` which are redirected with a special stream buffer.
On the other hand, `printf` really does not come with a hook for redirection unfortunately. There might be some hacky way to achieve this though.

**Comment by jurajmichalak1** [comment]
Thank you for such immediate answer. I'm sorry, I edited my previous comment.

**Comment by jurajmichalak1** [comment]
I remember that with python kernel when I use any native library (which does standard output) the output is printed into jupyter-notebook cell's output, so I would just stop with special std::cout... redirection and redirect directly file descriptors 2 (standard output) and 3 (standard error output). By the way I think that 3 is redirected by python kernel as red color text into cell's output. Then you just need to disable your c++ stdoutput buffer redirection and we can celebrate. Or please give me few directions into your source code and I'll check it.

**Comment by SylvainCorlay** [comment]
@jurajmichalak1 I meant that `std::cout` and `std::cerr` are already redirected to the front-end. We decided to not redirect `std::clog`.

Printf is not easily redirected.

**Comment by rene-fonseca** [comment]
I was hooking up xeus/cling for my library. But had an issue you may consider in the future.

As the current hook is done for the cout/cerr buffers it only works if the different libraries use the same shared libc++. For macOS at least xcpp is using @rpath/libxeus.1.dylib and comes with its own copy of libc++ dylib as part of the conda install. This means that the stdio hook doesn't work for any other libraries since these would normally be using the system libc++ (/usr/lib/libc++.1.dylib). Ie. the different libc++ states will be independent. For Windows it is very common to use different C runtime versions together so here it would be a common issue. For static C++ runtime linking, it will always be a problem.

Ideally the hook would be done at the file handle level instead - in which case nothing would need to be changed in the different libraries. This would required some work though.

Alternatively if we could dynamically detect when running in xeus/cling context we could switch to redirecting to a xeus/cling API for the output. However, this is not nice in the long run since it would require a specific xeus/cling build - instead of just using the same build for both non-cling and cling environments.

Let me know if you need more details.

For now I redirect everything internally in my lib and force the same libc++ (which is ok as long the same libc++ version is used as for xcpp).

**Comment by pdeitel** [comment]
How about an IPython-style "magic" command that allows folks to choose between C++ style and C style standard I/O?
