### ISSUE TITLE
xeus-cling kernel dies... but no log information

### ISSUE THREAD

**Issue by pkestene** [jupyter-xeus/xeus-cling#295]
Hello,

I'm using xeus-cling from jupyter, every thing is fine up to a point executing a given cell makes the kernel die, but nothing is logged in the console, only the popup window stating "The kernel appears to have died. It will restart automatically."

I saw the xeus doc stating I can set env variable XEUS_LOG before launching jupyter, but no difference, no log in console.

I'd just like to understand why the kernel dies, and I don't know how to go further.
Can somebody explain how should I increase log verbosity with xeus-cling ?
Thank you.

**Comment by pkestene** [comment]
I finally found my environment problem; I was trying to use [matplotlib-cpp](https://github.com/lava/matplotlib-cpp) and had some PYTHONUSERBASE variable set, which made the kernel crash.

I still don't know if it is easily possible to retrieve some verbous inside log to analyze what's happening when a kernel crash.

Thank you.

**Comment by JohanMabille** [comment]
Hi,

`XEUS_LOG` is more for logging Jupyter messages and debugging kernels based on xeus. It usually requires that you instantiate a logger and pass it to the `xeus::kernel` object used by your kernel implementation.

In the case of xeus-cling, we do not instantiate any logger since the kernel is now implemented and we do not need to debug the middleware layer anymore. So defining `XEUS_LOG` has no effect.

**Comment by pkestene** [comment]
thank you.
