### ISSUE TITLE
including .cpp files in xeus-cling

### ISSUE THREAD

**Issue by phesse001** [jupyter-xeus/xeus-cling#341]
So I am fairly new to cpp and I know that it is typically a BAD idea to include .cpp files anywhere do to multiple definitions of functions and classes. However, since this whole notebook acts as a sort of 'main' function, would this cause major problems? The reason I want to do this is that I can only put one function in a cell so I have to run like 10-20 cells before being able to run the main part of my program. I refactored by including all of the classes that my main function needs and the code ran the exact same. Will this cause issues/is this still a bad idea in xeus-cling? And are there any workarounds to this?(like any way to run a different notebook that compiles and uses that code in the current notebook).
Here is what it looked like before:
![xeus-cling-issue01](https://user-images.githubusercontent.com/61028064/83663350-5cdabe80-a58e-11ea-8463-5c17a6704507.PNG)
![xeus-cling-issue02](https://user-images.githubusercontent.com/61028064/83663368-62d09f80-a58e-11ea-8e9c-0efd7eb3d7fc.PNG)
![xeus-cling-issue03](https://user-images.githubusercontent.com/61028064/83663378-6532f980-a58e-11ea-8cf9-ace4965c38c6.PNG)
![xeus-cling-issue04](https://user-images.githubusercontent.com/61028064/83663387-66fcbd00-a58e-11ea-8394-2523d6648159.PNG)
![xeus-cling-issue05](https://user-images.githubusercontent.com/61028064/83663396-6a904400-a58e-11ea-80be-adae0c72eda1.PNG)
![xeus-cling-issue06](https://user-images.githubusercontent.com/61028064/83663403-6cf29e00-a58e-11ea-94be-6eb292a25245.PNG)
And this is it refactored:
![xeus-cling-issue07](https://user-images.githubusercontent.com/61028064/83663522-809e0480-a58e-11ea-9a66-ebf14317b8a8.PNG)

**Comment by phesse001** [comment]
The screenshots formatted horribly but the point is that I only have to run 3 cells vs 17 cells

**Comment by phesse001** [comment]
Found out I can just 'run above' for all the cells above which helps, but I'm still curious about the implications of including a .cpp file for refactoring in xeus-cling.

**Comment by JohanMabille** [comment]
Including a cpp file doe snot cause any problem as long as it is included in a single compilation unit in your project. It is usually considered as a bad practice to do so because you may end up including it in another compilation unit and then break the One Definition Rule (resulting in link error). Therefore it is usually better to extract a header from it and include the header.

Regarding the notebook, it is the only compilaiton unit you have so it's fine to include cpp files. However, if you start to have many cpp files, it might be worth building a library and use it in the notebook instead of building all the cpp files each time you execute the notebook.

Notice that, historically, including implementation files was somehow a pattern in C (not C++). The usage was to simulate what has become templates in C++:

```
// impl.c
TYPE compute(TYPE a, TYPE b)
{
    // Perform some computation
}

// myalgo.c
#define TYPE float
#include "impl.c"
#undef TYPE

#define TYPE double
#include "imp.c"
#undef TYPE
```

**Comment by phesse001** [comment]
Interesting, thanks for the feedback, that was my intuition but I wasn't sure if there were other reasons to not include implementation files other then the One Definition Rule. Thanks!
